//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MRV.Data.Model
{
    public partial class GHGDataEntryDetail
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int HeaderId
        {
            get { return _headerId; }
            set
            {
                if (_headerId != value)
                {
                    if (GHGDataEntryHeader != null && GHGDataEntryHeader.Id != value)
                    {
                        GHGDataEntryHeader = null;
                    }
                    _headerId = value;
                }
            }
        }
        private int _headerId;
    
        public virtual int ParameterId
        {
            get { return _parameterId; }
            set
            {
                if (_parameterId != value)
                {
                    if (GHGParameters != null && GHGParameters.Id != value)
                    {
                        GHGParameters = null;
                    }
                    _parameterId = value;
                }
            }
        }
        private int _parameterId;
    
        public virtual decimal Value
        {
            get;
            set;
        }
    
        public virtual string SourceOfData
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> UncertainityLevel
        {
            get;
            set;
        }
    
        public virtual bool IsDeleted
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual GHGDataEntryHeader GHGDataEntryHeader
        {
            get { return _gHGDataEntryHeader; }
            set
            {
                if (!ReferenceEquals(_gHGDataEntryHeader, value))
                {
                    var previousValue = _gHGDataEntryHeader;
                    _gHGDataEntryHeader = value;
                    FixupGHGDataEntryHeader(previousValue);
                }
            }
        }
        private GHGDataEntryHeader _gHGDataEntryHeader;
    
        public virtual GHGParameters GHGParameters
        {
            get { return _gHGParameters; }
            set
            {
                if (!ReferenceEquals(_gHGParameters, value))
                {
                    var previousValue = _gHGParameters;
                    _gHGParameters = value;
                    FixupGHGParameters(previousValue);
                }
            }
        }
        private GHGParameters _gHGParameters;

        #endregion

        #region Association Fixup
    
        private void FixupGHGDataEntryHeader(GHGDataEntryHeader previousValue)
        {
            if (previousValue != null && previousValue.GHGDataEntryDetail.Contains(this))
            {
                previousValue.GHGDataEntryDetail.Remove(this);
            }
    
            if (GHGDataEntryHeader != null)
            {
                if (!GHGDataEntryHeader.GHGDataEntryDetail.Contains(this))
                {
                    GHGDataEntryHeader.GHGDataEntryDetail.Add(this);
                }
                if (HeaderId != GHGDataEntryHeader.Id)
                {
                    HeaderId = GHGDataEntryHeader.Id;
                }
            }
        }
    
        private void FixupGHGParameters(GHGParameters previousValue)
        {
            if (previousValue != null && previousValue.GHGDataEntryDetail.Contains(this))
            {
                previousValue.GHGDataEntryDetail.Remove(this);
            }
    
            if (GHGParameters != null)
            {
                if (!GHGParameters.GHGDataEntryDetail.Contains(this))
                {
                    GHGParameters.GHGDataEntryDetail.Add(this);
                }
                if (ParameterId != GHGParameters.Id)
                {
                    ParameterId = GHGParameters.Id;
                }
            }
        }

        #endregion

    }
}
