//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MRV.Data.Model
{
    public partial class GHGInventoryYear
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual bool IsDeleted
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<GHGDataEntryHeader> GHGDataEntryHeader
        {
            get
            {
                if (_gHGDataEntryHeader == null)
                {
                    var newCollection = new FixupCollection<GHGDataEntryHeader>();
                    newCollection.CollectionChanged += FixupGHGDataEntryHeader;
                    _gHGDataEntryHeader = newCollection;
                }
                return _gHGDataEntryHeader;
            }
            set
            {
                if (!ReferenceEquals(_gHGDataEntryHeader, value))
                {
                    var previousValue = _gHGDataEntryHeader as FixupCollection<GHGDataEntryHeader>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGHGDataEntryHeader;
                    }
                    _gHGDataEntryHeader = value;
                    var newValue = value as FixupCollection<GHGDataEntryHeader>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGHGDataEntryHeader;
                    }
                }
            }
        }
        private ICollection<GHGDataEntryHeader> _gHGDataEntryHeader;

        #endregion

        #region Association Fixup
    
        private void FixupGHGDataEntryHeader(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GHGDataEntryHeader item in e.NewItems)
                {
                    item.GHGInventoryYear = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GHGDataEntryHeader item in e.OldItems)
                {
                    if (ReferenceEquals(item.GHGInventoryYear, this))
                    {
                        item.GHGInventoryYear = null;
                    }
                }
            }
        }

        #endregion

    }
}
