//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MRV.Data.Model
{
    public partial class GHGTypes
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }
    
        public virtual bool IsDeleted
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<GHGParameters> GHGParameters
        {
            get
            {
                if (_gHGParameters == null)
                {
                    var newCollection = new FixupCollection<GHGParameters>();
                    newCollection.CollectionChanged += FixupGHGParameters;
                    _gHGParameters = newCollection;
                }
                return _gHGParameters;
            }
            set
            {
                if (!ReferenceEquals(_gHGParameters, value))
                {
                    var previousValue = _gHGParameters as FixupCollection<GHGParameters>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGHGParameters;
                    }
                    _gHGParameters = value;
                    var newValue = value as FixupCollection<GHGParameters>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGHGParameters;
                    }
                }
            }
        }
        private ICollection<GHGParameters> _gHGParameters;

        #endregion

        #region Association Fixup
    
        private void FixupGHGParameters(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GHGParameters item in e.NewItems)
                {
                    item.GHGTypes = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GHGParameters item in e.OldItems)
                {
                    if (ReferenceEquals(item.GHGTypes, this))
                    {
                        item.GHGTypes = null;
                    }
                }
            }
        }

        #endregion

    }
}
