//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MRV.Data.Model
{
    public partial class sysMenus
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SystemId
        {
            get { return _systemId; }
            set
            {
                if (_systemId != value)
                {
                    if (sysSystems != null && sysSystems.Id != value)
                    {
                        sysSystems = null;
                    }
                    _systemId = value;
                }
            }
        }
        private int _systemId;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }
    
        public virtual string IconCls
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual sysSystems sysSystems
        {
            get { return _sysSystems; }
            set
            {
                if (!ReferenceEquals(_sysSystems, value))
                {
                    var previousValue = _sysSystems;
                    _sysSystems = value;
                    FixupsysSystems(previousValue);
                }
            }
        }
        private sysSystems _sysSystems;
    
        public virtual ICollection<sysSubMenu> sysSubMenu
        {
            get
            {
                if (_sysSubMenu == null)
                {
                    var newCollection = new FixupCollection<sysSubMenu>();
                    newCollection.CollectionChanged += FixupsysSubMenu;
                    _sysSubMenu = newCollection;
                }
                return _sysSubMenu;
            }
            set
            {
                if (!ReferenceEquals(_sysSubMenu, value))
                {
                    var previousValue = _sysSubMenu as FixupCollection<sysSubMenu>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupsysSubMenu;
                    }
                    _sysSubMenu = value;
                    var newValue = value as FixupCollection<sysSubMenu>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupsysSubMenu;
                    }
                }
            }
        }
        private ICollection<sysSubMenu> _sysSubMenu;

        #endregion

        #region Association Fixup
    
        private void FixupsysSystems(sysSystems previousValue)
        {
            if (previousValue != null && previousValue.sysMenus.Contains(this))
            {
                previousValue.sysMenus.Remove(this);
            }
    
            if (sysSystems != null)
            {
                if (!sysSystems.sysMenus.Contains(this))
                {
                    sysSystems.sysMenus.Add(this);
                }
                if (SystemId != sysSystems.Id)
                {
                    SystemId = sysSystems.Id;
                }
            }
        }
    
        private void FixupsysSubMenu(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (sysSubMenu item in e.NewItems)
                {
                    item.sysMenus = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (sysSubMenu item in e.OldItems)
                {
                    if (ReferenceEquals(item.sysMenus, this))
                    {
                        item.sysMenus = null;
                    }
                }
            }
        }

        #endregion

    }
}
