//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MRV.Data.Model
{
    public partial class sysUserSystems
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (sysUser != null && sysUser.Id != value)
                    {
                        sysUser = null;
                    }
                    _userId = value;
                }
            }
        }
        private int _userId;
    
        public virtual int SystemId
        {
            get { return _systemId; }
            set
            {
                if (_systemId != value)
                {
                    if (sysSystems != null && sysSystems.Id != value)
                    {
                        sysSystems = null;
                    }
                    _systemId = value;
                }
            }
        }
        private int _systemId;

        #endregion

        #region Navigation Properties
    
        public virtual sysSystems sysSystems
        {
            get { return _sysSystems; }
            set
            {
                if (!ReferenceEquals(_sysSystems, value))
                {
                    var previousValue = _sysSystems;
                    _sysSystems = value;
                    FixupsysSystems(previousValue);
                }
            }
        }
        private sysSystems _sysSystems;
    
        public virtual sysUser sysUser
        {
            get { return _sysUser; }
            set
            {
                if (!ReferenceEquals(_sysUser, value))
                {
                    var previousValue = _sysUser;
                    _sysUser = value;
                    FixupsysUser(previousValue);
                }
            }
        }
        private sysUser _sysUser;

        #endregion

        #region Association Fixup
    
        private void FixupsysSystems(sysSystems previousValue)
        {
            if (previousValue != null && previousValue.sysUserSystems.Contains(this))
            {
                previousValue.sysUserSystems.Remove(this);
            }
    
            if (sysSystems != null)
            {
                if (!sysSystems.sysUserSystems.Contains(this))
                {
                    sysSystems.sysUserSystems.Add(this);
                }
                if (SystemId != sysSystems.Id)
                {
                    SystemId = sysSystems.Id;
                }
            }
        }
    
        private void FixupsysUser(sysUser previousValue)
        {
            if (previousValue != null && previousValue.sysUserSystems.Contains(this))
            {
                previousValue.sysUserSystems.Remove(this);
            }
    
            if (sysUser != null)
            {
                if (!sysUser.sysUserSystems.Contains(this))
                {
                    sysUser.sysUserSystems.Add(this);
                }
                if (UserId != sysUser.Id)
                {
                    UserId = sysUser.Id;
                }
            }
        }

        #endregion

    }
}
