//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MRV.Data.Model
{
    public partial class sysUserRole
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> UserId
        {
            get { return _userId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_userId != value)
                    {
                        if (sysUser != null && sysUser.Id != value)
                        {
                            sysUser = null;
                        }
                        _userId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _userId;
    
        public virtual Nullable<int> RoleId
        {
            get { return _roleId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_roleId != value)
                    {
                        if (sysRole != null && sysRole.Id != value)
                        {
                            sysRole = null;
                        }
                        _roleId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _roleId;

        #endregion

        #region Navigation Properties
    
        public virtual sysRole sysRole
        {
            get { return _sysRole; }
            set
            {
                if (!ReferenceEquals(_sysRole, value))
                {
                    var previousValue = _sysRole;
                    _sysRole = value;
                    FixupsysRole(previousValue);
                }
            }
        }
        private sysRole _sysRole;
    
        public virtual sysUser sysUser
        {
            get { return _sysUser; }
            set
            {
                if (!ReferenceEquals(_sysUser, value))
                {
                    var previousValue = _sysUser;
                    _sysUser = value;
                    FixupsysUser(previousValue);
                }
            }
        }
        private sysUser _sysUser;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupsysRole(sysRole previousValue)
        {
            if (previousValue != null && previousValue.sysUserRole.Contains(this))
            {
                previousValue.sysUserRole.Remove(this);
            }
    
            if (sysRole != null)
            {
                if (!sysRole.sysUserRole.Contains(this))
                {
                    sysRole.sysUserRole.Add(this);
                }
                if (RoleId != sysRole.Id)
                {
                    RoleId = sysRole.Id;
                }
            }
            else if (!_settingFK)
            {
                RoleId = null;
            }
        }
    
        private void FixupsysUser(sysUser previousValue)
        {
            if (previousValue != null && previousValue.sysUserRole.Contains(this))
            {
                previousValue.sysUserRole.Remove(this);
            }
    
            if (sysUser != null)
            {
                if (!sysUser.sysUserRole.Contains(this))
                {
                    sysUser.sysUserRole.Add(this);
                }
                if (UserId != sysUser.Id)
                {
                    UserId = sysUser.Id;
                }
            }
            else if (!_settingFK)
            {
                UserId = null;
            }
        }

        #endregion

    }
}
