//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace MRV.Data.Model
{
    public partial class ENTRO_MISEntities : ObjectContext
    {
        public const string ConnectionString = "name=ENTRO_MISEntities";
        public const string ContainerName = "ENTRO_MISEntities";
    
        #region Constructors
    
        public ENTRO_MISEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ENTRO_MISEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ENTRO_MISEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<GHGDataEntryDetail> GHGDataEntryDetail
        {
            get { return _gHGDataEntryDetail  ?? (_gHGDataEntryDetail = CreateObjectSet<GHGDataEntryDetail>("GHGDataEntryDetail")); }
        }
        private ObjectSet<GHGDataEntryDetail> _gHGDataEntryDetail;
    
        public ObjectSet<GHGDataEntryHeader> GHGDataEntryHeader
        {
            get { return _gHGDataEntryHeader  ?? (_gHGDataEntryHeader = CreateObjectSet<GHGDataEntryHeader>("GHGDataEntryHeader")); }
        }
        private ObjectSet<GHGDataEntryHeader> _gHGDataEntryHeader;
    
        public ObjectSet<GHGDataTypes> GHGDataTypes
        {
            get { return _gHGDataTypes  ?? (_gHGDataTypes = CreateObjectSet<GHGDataTypes>("GHGDataTypes")); }
        }
        private ObjectSet<GHGDataTypes> _gHGDataTypes;
    
        public ObjectSet<GHGInventoryYear> GHGInventoryYear
        {
            get { return _gHGInventoryYear  ?? (_gHGInventoryYear = CreateObjectSet<GHGInventoryYear>("GHGInventoryYear")); }
        }
        private ObjectSet<GHGInventoryYear> _gHGInventoryYear;
    
        public ObjectSet<GHGParameters> GHGParameters
        {
            get { return _gHGParameters  ?? (_gHGParameters = CreateObjectSet<GHGParameters>("GHGParameters")); }
        }
        private ObjectSet<GHGParameters> _gHGParameters;
    
        public ObjectSet<GHGSectors> GHGSectors
        {
            get { return _gHGSectors  ?? (_gHGSectors = CreateObjectSet<GHGSectors>("GHGSectors")); }
        }
        private ObjectSet<GHGSectors> _gHGSectors;
    
        public ObjectSet<GHGTypes> GHGTypes
        {
            get { return _gHGTypes  ?? (_gHGTypes = CreateObjectSet<GHGTypes>("GHGTypes")); }
        }
        private ObjectSet<GHGTypes> _gHGTypes;
    
        public ObjectSet<GHGUnits> GHGUnits
        {
            get { return _gHGUnits  ?? (_gHGUnits = CreateObjectSet<GHGUnits>("GHGUnits")); }
        }
        private ObjectSet<GHGUnits> _gHGUnits;
    
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get { return _sysdiagrams  ?? (_sysdiagrams = CreateObjectSet<sysdiagrams>("sysdiagrams")); }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        public ObjectSet<sysMenus> sysMenus
        {
            get { return _sysMenus  ?? (_sysMenus = CreateObjectSet<sysMenus>("sysMenus")); }
        }
        private ObjectSet<sysMenus> _sysMenus;
    
        public ObjectSet<sysRole> sysRole
        {
            get { return _sysRole  ?? (_sysRole = CreateObjectSet<sysRole>("sysRole")); }
        }
        private ObjectSet<sysRole> _sysRole;
    
        public ObjectSet<sysRolePermission> sysRolePermission
        {
            get { return _sysRolePermission  ?? (_sysRolePermission = CreateObjectSet<sysRolePermission>("sysRolePermission")); }
        }
        private ObjectSet<sysRolePermission> _sysRolePermission;
    
        public ObjectSet<sysSubMenu> sysSubMenu
        {
            get { return _sysSubMenu  ?? (_sysSubMenu = CreateObjectSet<sysSubMenu>("sysSubMenu")); }
        }
        private ObjectSet<sysSubMenu> _sysSubMenu;
    
        public ObjectSet<sysSystems> sysSystems
        {
            get { return _sysSystems  ?? (_sysSystems = CreateObjectSet<sysSystems>("sysSystems")); }
        }
        private ObjectSet<sysSystems> _sysSystems;
    
        public ObjectSet<sysUser> sysUser
        {
            get { return _sysUser  ?? (_sysUser = CreateObjectSet<sysUser>("sysUser")); }
        }
        private ObjectSet<sysUser> _sysUser;
    
        public ObjectSet<sysUserRole> sysUserRole
        {
            get { return _sysUserRole  ?? (_sysUserRole = CreateObjectSet<sysUserRole>("sysUserRole")); }
        }
        private ObjectSet<sysUserRole> _sysUserRole;
    
        public ObjectSet<sysUserSystems> sysUserSystems
        {
            get { return _sysUserSystems  ?? (_sysUserSystems = CreateObjectSet<sysUserSystems>("sysUserSystems")); }
        }
        private ObjectSet<sysUserSystems> _sysUserSystems;
    
        public ObjectSet<GHGLocations> GHGLocations
        {
            get { return _gHGLocations  ?? (_gHGLocations = CreateObjectSet<GHGLocations>("GHGLocations")); }
        }
        private ObjectSet<GHGLocations> _gHGLocations;
    
        public ObjectSet<GHGLocationTypes> GHGLocationTypes
        {
            get { return _gHGLocationTypes  ?? (_gHGLocationTypes = CreateObjectSet<GHGLocationTypes>("GHGLocationTypes")); }
        }
        private ObjectSet<GHGLocationTypes> _gHGLocationTypes;

        #endregion

    }
}
